name: spin_wheel_app
description: A simple spin wheel app.
publish_to: 'none' # Prevents accidental publishing to pub.dev.

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
